<?php
class testing_AutoGeneratedException extends PHPUnit_Framework_AssertionFailedError
{
	/**
	 * Wrapper for getMessage() which is declared as final.
	 *
	 * @return string
	 */
	public function toString()
	{
		$this->message .= 'Auto generated test. Not implemented yet';
		return $this->getMessage();
	}
}