<?php

/**
 * Base test case.
 */
class testing_UnitTestBase extends PHPUnit_Framework_TestCase
{

	/**
	 * Prepares the environment before running a test.
	 */
	protected function setUp()
	{
		parent::setUp();

		$this->setRunTestInSeparateProcess(true);
	}

	/**
	 * Cleans up the environment after running a test.
	 */
	protected function tearDown()
	{
		parent::tearDown();
	}
	
	/**
	 * Failed the test with particular exception and message.
	 * 
	 * @param  string   $message
	 * @throws testing_AutoGeneratedException
	 */
	protected function markTestAutoGenereted($message = '')
	{
		throw new testing_AutoGeneratedException($message);
	}
	
}

