
	/**
	 * Tests <{$classbase}>-><{$method}>()
	 * @see <{$classbase}>::<{$method}>
	 */
	public function test<{$uMethod}>()
	{
		//remove this method after edited the test
		$this->markTestAutoGenerated();
	}
	